# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'once_run.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_once_run(object):
    def setupUi(self, once_run):
        once_run.setObjectName("once_run")
        once_run.resize(1065, 482)
        self.once_run_table = QtWidgets.QTableWidget(once_run)
        self.once_run_table.setGeometry(QtCore.QRect(10, 10, 1041, 400))
        self.once_run_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.once_run_table.setObjectName("once_run_table")
        self.once_run_table.setColumnCount(9)
        self.once_run_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.once_run_table.setHorizontalHeaderItem(8, item)
        self.avg_lb = QtWidgets.QLabel(once_run)
        self.avg_lb.setGeometry(QtCore.QRect(30, 440, 111, 21))
        self.avg_lb.setObjectName("avg_lb")
        self.avg_txt = QtWidgets.QTextBrowser(once_run)
        self.avg_txt.setGeometry(QtCore.QRect(130, 440, 81, 21))
        self.avg_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.avg_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.avg_txt.setObjectName("avg_txt")
        self.sys_use_lb = QtWidgets.QLabel(once_run)
        self.sys_use_lb.setGeometry(QtCore.QRect(260, 440, 81, 21))
        self.sys_use_lb.setObjectName("sys_use_lb")
        self.sys_use_txt = QtWidgets.QTextBrowser(once_run)
        self.sys_use_txt.setGeometry(QtCore.QRect(350, 440, 81, 21))
        self.sys_use_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sys_use_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sys_use_txt.setObjectName("sys_use_txt")
        self.help_btn = QtWidgets.QPushButton(once_run)
        self.help_btn.setGeometry(QtCore.QRect(850, 440, 75, 23))
        self.help_btn.setObjectName("help_btn")
        self.finish_btn = QtWidgets.QPushButton(once_run)
        self.finish_btn.setGeometry(QtCore.QRect(750, 440, 75, 23))
        self.finish_btn.setObjectName("finish_btn")
        self.clr_cache_btn = QtWidgets.QPushButton(once_run)
        self.clr_cache_btn.setGeometry(QtCore.QRect(624, 440, 101, 23))
        self.clr_cache_btn.setObjectName("clr_cache_btn")
        self.once_run_btn = QtWidgets.QPushButton(once_run)
        self.once_run_btn.setGeometry(QtCore.QRect(520, 440, 75, 23))
        self.once_run_btn.setObjectName("once_run_btn")

        self.retranslateUi(once_run)
        QtCore.QMetaObject.connectSlotsByName(once_run)

    def retranslateUi(self, once_run):
        _translate = QtCore.QCoreApplication.translate
        once_run.setWindowTitle(_translate("once_run", "运行一次"))
        item = self.once_run_table.verticalHeaderItem(0)
        item.setText(_translate("once_run", "**"))
        item = self.once_run_table.horizontalHeaderItem(0)
        item.setText(_translate("once_run", "客户编号"))
        item = self.once_run_table.horizontalHeaderItem(1)
        item.setText(_translate("once_run", "间隔时间"))
        item = self.once_run_table.horizontalHeaderItem(2)
        item.setText(_translate("once_run", "到达时间"))
        item = self.once_run_table.horizontalHeaderItem(3)
        item.setText(_translate("once_run", "服务时间"))
        item = self.once_run_table.horizontalHeaderItem(4)
        item.setText(_translate("once_run", "服务开始时间"))
        item = self.once_run_table.horizontalHeaderItem(5)
        item.setText(_translate("once_run", "等待时间"))
        item = self.once_run_table.horizontalHeaderItem(6)
        item.setText(_translate("once_run", "服务结束时间"))
        item = self.once_run_table.horizontalHeaderItem(7)
        item.setText(_translate("once_run", "客户在系统花费时间"))
        item = self.once_run_table.horizontalHeaderItem(8)
        item.setText(_translate("once_run", "空闲时间"))
        self.avg_lb.setText(_translate("once_run", "平均等待时间："))
        self.sys_use_lb.setText(_translate("once_run", "系统利用率："))
        self.help_btn.setText(_translate("once_run", "帮助"))
        self.finish_btn.setText(_translate("once_run", "完成"))
        self.clr_cache_btn.setText(_translate("once_run", "清除缓存数据"))
        self.once_run_btn.setText(_translate("once_run", "运行一次"))

