from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
class new_patient(QWidget):
    def __init__(self,parent=None):
        super().__init__(parent)#相当于下面那句
        self.setupUI()
    def setupUI(self):
        self.setGeometry(QtCore.QRect(220, 60, 981, 671))
        self.setObjectName("newCondIntv_widget")
        self.page_title_label = QtWidgets.QLabel(self)
        self.page_title_label.setGeometry(QtCore.QRect(370, 30, 201, 61))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.page_title_label.setFont(font)
        self.page_title_label.setObjectName("page_title_label")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(389, 569, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.checkBox00 = QtWidgets.QCheckBox(self)
        self.checkBox00.setGeometry(QtCore.QRect(130, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox00.setFont(font)
        self.checkBox00.setObjectName("checkBox00")
        self.checkBox02 = QtWidgets.QCheckBox(self)
        self.checkBox02.setGeometry(QtCore.QRect(410, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox02.setFont(font)
        self.checkBox02.setObjectName("checkBox02")
        self.checkBox01 = QtWidgets.QCheckBox(self)
        self.checkBox01.setGeometry(QtCore.QRect(260, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox01.setFont(font)
        self.checkBox01.setObjectName("checkBox01")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(60, 100, 51, 21))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 51, 21))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.checkBox10 = QtWidgets.QCheckBox(self)
        self.checkBox10.setGeometry(QtCore.QRect(130, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox10.setFont(font)
        self.checkBox10.setObjectName("checkBox10")
        self.checkBox11 = QtWidgets.QCheckBox(self)
        self.checkBox11.setGeometry(QtCore.QRect(220, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox11.setFont(font)
        self.checkBox11.setObjectName("checkBox11")
        self.checkBox12 = QtWidgets.QCheckBox(self)
        self.checkBox12.setGeometry(QtCore.QRect(310, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox12.setFont(font)
        self.checkBox12.setObjectName("checkBox12")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(60, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox20 = QtWidgets.QCheckBox(self)
        self.checkBox20.setGeometry(QtCore.QRect(130, 240, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox20.setFont(font)
        self.checkBox20.setObjectName("checkBox20")
        self.checkBox21 = QtWidgets.QCheckBox(self)
        self.checkBox21.setGeometry(QtCore.QRect(230, 240, 61, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox21.setFont(font)
        self.checkBox21.setObjectName("checkBox21")
        self.checkBox22 = QtWidgets.QCheckBox(self)
        self.checkBox22.setGeometry(QtCore.QRect(320, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox22.setFont(font)
        self.checkBox22.setObjectName("checkBox22")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(60, 310, 51, 21))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox30 = QtWidgets.QCheckBox(self)
        self.checkBox30.setGeometry(QtCore.QRect(130, 310, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox30.setFont(font)
        self.checkBox30.setObjectName("checkBox30")
        self.checkBox40 = QtWidgets.QCheckBox(self)
        self.checkBox40.setGeometry(QtCore.QRect(140, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox40.setFont(font)
        self.checkBox40.setObjectName("checkBox40")
        self.checkBox41 = QtWidgets.QCheckBox(self)
        self.checkBox41.setGeometry(QtCore.QRect(240, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox41.setFont(font)
        self.checkBox41.setObjectName("checkBox41")
        self.checkBox42 = QtWidgets.QCheckBox(self)
        self.checkBox42.setGeometry(QtCore.QRect(350, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox42.setFont(font)
        self.checkBox42.setObjectName("checkBox42")
        self.textBrowser = QtWidgets.QTextBrowser(self)
        self.textBrowser.setGeometry(QtCore.QRect(620, 110, 331, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.checkBox03 = QtWidgets.QCheckBox(self)
        self.checkBox03.setGeometry(QtCore.QRect(520, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox03.setFont(font)
        self.checkBox03.setObjectName("checkBox03")
        self.checkBox13 = QtWidgets.QCheckBox(self)
        self.checkBox13.setGeometry(QtCore.QRect(420, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox13.setFont(font)
        self.checkBox13.setObjectName("checkBox13")
        self.checkBox31 = QtWidgets.QCheckBox(self)
        self.checkBox31.setGeometry(QtCore.QRect(220, 310, 71, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox31.setFont(font)
        self.checkBox31.setObjectName("checkBox31")
        self.checkBox32 = QtWidgets.QCheckBox(self)
        self.checkBox32.setGeometry(QtCore.QRect(310, 310, 131, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox32.setFont(font)
        self.checkBox32.setObjectName("checkBox32")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(60, 380, 51, 21))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox43 = QtWidgets.QCheckBox(self)
        self.checkBox43.setGeometry(QtCore.QRect(450, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox43.setFont(font)
        self.checkBox43.setObjectName("checkBox43")
        self.checkBox44 = QtWidgets.QCheckBox(self)
        self.checkBox44.setGeometry(QtCore.QRect(140, 410, 71, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox44.setFont(font)
        self.checkBox44.setObjectName("checkBox44")
        self.checkBox45 = QtWidgets.QCheckBox(self)
        self.checkBox45.setGeometry(QtCore.QRect(240, 410, 71, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox45.setFont(font)
        self.checkBox45.setObjectName("checkBox45")
        self.checkBox46 = QtWidgets.QCheckBox(self)
        self.checkBox46.setGeometry(QtCore.QRect(350, 410, 71, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox46.setFont(font)
        self.checkBox46.setObjectName("checkBox46")
        self.checkBox47 = QtWidgets.QCheckBox(self)
        self.checkBox47.setGeometry(QtCore.QRect(450, 410, 191, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox47.setFont(font)
        self.checkBox47.setObjectName("checkBox47")

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.page_title_label.setText(_translate("Form", "新建病情调查"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.checkBox00.setText(_translate("Form", "低热（37-38）"))
        self.checkBox02.setText(_translate("Form", "畏寒"))
        self.checkBox01.setText(_translate("Form", "发烧（38以上）"))
        self.label.setText(_translate("Form", "全身："))
        self.label_2.setText(_translate("Form", "头部："))
        self.checkBox10.setText(_translate("Form", "鼻塞"))
        self.checkBox11.setText(_translate("Form", "喷嚏"))
        self.checkBox12.setText(_translate("Form", "咳嗽（轻）"))
        self.label_3.setText(_translate("Form", "颈部："))
        self.checkBox20.setText(_translate("Form", "咽干咽痒"))
        self.checkBox21.setText(_translate("Form", "咽痛"))
        self.checkBox22.setText(_translate("Form", "咽部重血"))
        self.label_4.setText(_translate("Form", "胸部："))
        self.checkBox30.setText(_translate("Form", "咳嗽（重）"))
        self.checkBox40.setText(_translate("Form", "上腹痛"))
        self.checkBox41.setText(_translate("Form", "食欲不振"))
        self.checkBox42.setText(_translate("Form", "嗳气"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'Noto Sans CJK SC\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">提示：</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          本功能为演示功能，由于缺乏专业数据库</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          支持，   您只有在选择特定几种组合时，数</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          据库中会查找出您的病情 对于其他组合，</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          可能会误诊。</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">例子：</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          选择低热，发烧，畏寒，酸痛疲乏，鼻涕，咳嗽</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">         头痛，咽干咽痒，诊断为感冒。</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">     </span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">         选择腹部上腹痛，食欲不振，嗳气，恶心</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">        呕吐，会诊断为胃炎</span></p></body></html>"))
        self.checkBox03.setText(_translate("Form", "酸痛疲乏"))
        self.checkBox13.setText(_translate("Form", "头痛"))
        self.checkBox31.setText(_translate("Form", "咳痰"))
        self.checkBox32.setText(_translate("Form", "支气管痉挛"))
        self.label_5.setText(_translate("Form", "腹部"))
        self.checkBox43.setText(_translate("Form", "恶心"))
        self.checkBox44.setText(_translate("Form", "呕吐"))
        self.checkBox45.setText(_translate("Form", "腹泻"))
        self.checkBox46.setText(_translate("Form", "腹痛"))
        self.checkBox47.setText(_translate("Form", "吃油腻食物右上腹部剧痛"))

        self.page_title_label.setText(_translate("Form", "新建病情调查"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.checkBox00.setText(_translate("Form", "低热（37-38）"))
        self.checkBox02.setText(_translate("Form", "畏寒"))
        self.checkBox01.setText(_translate("Form", "发烧（38以上）"))
        self.label.setText(_translate("Form", "全身："))
        self.label_2.setText(_translate("Form", "头部："))
        self.checkBox10.setText(_translate("Form", "鼻塞"))
        self.checkBox11.setText(_translate("Form", "喷嚏"))
        self.checkBox12.setText(_translate("Form", "咳嗽（轻）"))
        self.label_3.setText(_translate("Form", "颈部："))
        self.checkBox20.setText(_translate("Form", "咽干咽痒"))
        self.checkBox21.setText(_translate("Form", "咽痛"))
        self.checkBox22.setText(_translate("Form", "咽部重血"))
        self.label_4.setText(_translate("Form", "胸部："))
        self.checkBox30.setText(_translate("Form", "咳嗽（重）"))
        self.checkBox40.setText(_translate("Form", "上腹痛"))
        self.checkBox41.setText(_translate("Form", "食欲不振"))
        self.checkBox42.setText(_translate("Form", "嗳气"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans CJK SC\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">提示：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          本功能为演示功能，由于缺乏专业数据库</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          支持，   您只有在选择特定几种组合时，数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          据库中会查找出您的病情 对于其他组合，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          可能会误诊。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">例子：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">          选择低热，发烧，畏寒，酸痛疲乏，鼻涕，咳嗽</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">         头痛，咽干咽痒，诊断为感冒。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">     </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">         选择腹部上腹痛，食欲不振，嗳气，恶心</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">        呕吐，会诊断为胃炎</span></p></body></html>"))
        self.checkBox03.setText(_translate("Form", "酸痛疲乏"))
        self.checkBox13.setText(_translate("Form", "头痛"))
        self.checkBox31.setText(_translate("Form", "咳痰"))
        self.checkBox32.setText(_translate("Form", "支气管痉挛"))
        self.label_5.setText(_translate("Form", "腹部"))
        self.checkBox43.setText(_translate("Form", "恶心"))
        self.checkBox44.setText(_translate("Form", "呕吐"))
        self.checkBox45.setText(_translate("Form", "腹泻"))
        self.checkBox46.setText(_translate("Form", "腹痛"))
        self.checkBox47.setText(_translate("Form", "吃油腻食物右上腹部剧痛"))

