from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
class PMD_detail_widget(QWidget):
    def __init__(self,parent=None):
        super().__init__(parent)#相当于下面那句
        self.setupUI()
    def setupUI(self):
        self.setGeometry(QtCore.QRect(259, 29, 981, 671))
        self.setObjectName("PMD_detail_widget")
        self.page_title_label = QtWidgets.QLabel(self)
        self.page_title_label.setGeometry(QtCore.QRect(410, 0, 141, 61))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.page_title_label.setFont(font)
        self.page_title_label.setObjectName("page_title_label")
        self.PMD_head_label = QtWidgets.QLabel(self)
        self.PMD_head_label.setGeometry(QtCore.QRect(40, 70, 181, 171))
        self.PMD_head_label.setText("")
        self.PMD_head_label.setPixmap(QtGui.QPixmap("source/医生.png"))
        self.PMD_head_label.setScaledContents(True)
        self.PMD_head_label.setObjectName("PMD_head_label")
        self.PMDinfo_textBrowser = QtWidgets.QTextBrowser(self)
        self.PMDinfo_textBrowser.setGeometry(QtCore.QRect(290, 60, 561, 171))
        self.PMDinfo_textBrowser.setObjectName("PMDinfo_textBrowser")
        self.name_label = QtWidgets.QLabel(self)
        self.name_label.setGeometry(QtCore.QRect(70, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.one_line = QtWidgets.QFrame(self)
        self.one_line.setGeometry(QtCore.QRect(233, 60, 31, 171))
        self.one_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.one_line.setLineWidth(5)
        self.one_line.setMidLineWidth(0)
        self.one_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.one_line.setObjectName("one_line")
        self.name_info_label = QtWidgets.QLabel(self)
        self.name_info_label.setGeometry(QtCore.QRect(180, 280, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name_info_label.setFont(font)
        self.name_info_label.setObjectName("name_info_label")
        self.hospital_info_label = QtWidgets.QLabel(self)
        self.hospital_info_label.setGeometry(QtCore.QRect(180, 320, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hospital_info_label.setFont(font)
        self.hospital_info_label.setObjectName("hospital_info_label")
        self.hospital_label = QtWidgets.QLabel(self)
        self.hospital_label.setGeometry(QtCore.QRect(70, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hospital_label.setFont(font)
        self.hospital_label.setObjectName("hospital_label")
        self.title_info_label = QtWidgets.QLabel(self)
        self.title_info_label.setGeometry(QtCore.QRect(180, 360, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_info_label.setFont(font)
        self.title_info_label.setObjectName("title_info_label")
        self.title_label = QtWidgets.QLabel(self)
        self.title_label.setGeometry(QtCore.QRect(70, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.replay_info_label = QtWidgets.QLabel(self)
        self.replay_info_label.setGeometry(QtCore.QRect(180, 400, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.replay_info_label.setFont(font)
        self.replay_info_label.setObjectName("replay_info_label")
        self.reply_label = QtWidgets.QLabel(self)
        self.reply_label.setGeometry(QtCore.QRect(70, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reply_label.setFont(font)
        self.reply_label.setObjectName("reply_label")
        self.two_line = QtWidgets.QFrame(self)
        self.two_line.setGeometry(QtCore.QRect(360, 270, 31, 171))
        self.two_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.two_line.setLineWidth(3)
        self.two_line.setMidLineWidth(0)
        self.two_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.two_line.setObjectName("two_line")
        self.age_info_label = QtWidgets.QLabel(self)
        self.age_info_label.setGeometry(QtCore.QRect(560, 280, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.age_info_label.setFont(font)
        self.age_info_label.setObjectName("age_info_label")
        self.age_label = QtWidgets.QLabel(self)
        self.age_label.setGeometry(QtCore.QRect(450, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.age_label.setFont(font)
        self.age_label.setObjectName("age_label")
        self.department_info_label = QtWidgets.QLabel(self)
        self.department_info_label.setGeometry(QtCore.QRect(560, 320, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.department_info_label.setFont(font)
        self.department_info_label.setObjectName("department_info_label")
        self.department_label = QtWidgets.QLabel(self)
        self.department_label.setGeometry(QtCore.QRect(450, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.department_label.setFont(font)
        self.department_label.setObjectName("department_label")
        self.satisfaction_info_label = QtWidgets.QLabel(self)
        self.satisfaction_info_label.setGeometry(QtCore.QRect(560, 360, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.satisfaction_info_label.setFont(font)
        self.satisfaction_info_label.setObjectName("satisfaction_info_label")
        self.satisfaction_label = QtWidgets.QLabel(self)
        self.satisfaction_label.setGeometry(QtCore.QRect(450, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.satisfaction_label.setFont(font)
        self.satisfaction_label.setObjectName("satisfaction_label")
        self.stars_info_label = QtWidgets.QLabel(self)
        self.stars_info_label.setGeometry(QtCore.QRect(560, 400, 171, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stars_info_label.setFont(font)
        self.stars_info_label.setObjectName("stars_info_label")
        self.stars_label = QtWidgets.QLabel(self)
        self.stars_label.setGeometry(QtCore.QRect(450, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stars_label.setFont(font)
        self.stars_label.setObjectName("stars_label")
        self.chose_Button = QtWidgets.QPushButton(self)
        self.chose_Button.setGeometry(QtCore.QRect(70, 480, 191, 41))
        self.chose_Button.setObjectName("chose_Button")

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.page_title_label.setText(_translate("Form", "医生详情"))
        self.PMDinfo_textBrowser.setHtml(_translate("Form",
                                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'Noto Sans CJK SC\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">打分信息</span></p>\n"
                                                    "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">目前病人排队信息</span></p>\n"
                                                    "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">.......</span></p></body></html>"))
        self.name_label.setText(_translate("Form", "姓名："))
        self.name_info_label.setText(_translate("Form", "马景春"))
        self.hospital_info_label.setText(_translate("Form", "开发区医院"))
        self.hospital_label.setText(_translate("Form", "医院："))
        self.title_info_label.setText(_translate("Form", "主治医师"))
        self.title_label.setText(_translate("Form", "职称："))
        self.replay_info_label.setText(_translate("Form", "90%"))
        self.reply_label.setText(_translate("Form", "回复率："))
        self.age_info_label.setText(_translate("Form", "56"))
        self.age_label.setText(_translate("Form", "年龄："))
        self.department_info_label.setText(_translate("Form", "儿科"))
        self.department_label.setText(_translate("Form", "科室："))
        self.satisfaction_info_label.setText(_translate("Form", "90"))
        self.satisfaction_label.setText(_translate("Form", "满意度："))
        self.stars_info_label.setText(_translate("Form", "5/5"))
        self.stars_label.setText(_translate("Form", "态度星级："))
        self.chose_Button.setText(_translate("Form", "选择签约"))

