# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Child(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1722, 745)
        MainWindow.setStyleSheet("\n"
" \n"
"background-color: rgb(170, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(205, 2, 1191, 656))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(" color: rgb(255, 255, 255);")
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_36.setOpenExternalLinks(True)
        self.label_36.setObjectName("label_36")
        self.verticalLayout.addWidget(self.label_36)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_12.setOpenExternalLinks(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_13.setOpenExternalLinks(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        # self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        # font = QtGui.QFont()
        # font.setFamily("Agency FB")
        # font.setPointSize(12)
        # font.setBold(True)
        # font.setWeight(75)
        # self.label_14.setFont(font)
        # self.label_14.setStyleSheet("color :rgb(255, 255, 255)")
        # self.label_14.setOpenExternalLinks(True)
        # self.label_14.setObjectName("label_14")
        # self.verticalLayout.addWidget(self.label_14)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_11.setOpenExternalLinks(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_15.setOpenExternalLinks(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_30.setObjectName("label_30")
        self.verticalLayout.addWidget(self.label_30)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)

        # 增加，增加和修改12.1 关键字竞价排名
        self.label_123 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_123.setFont(font)
        self.label_123.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_123.setOpenExternalLinks(True)
        self.label_123.setObjectName("label_123")
        self.verticalLayout_2.addWidget(self.label_123)

        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_26.setOpenExternalLinks(True)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_28.setOpenExternalLinks(True)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        # self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        # font = QtGui.QFont()
        # font.setFamily("Agency FB")
        # font.setPointSize(12)
        # font.setBold(True)
        # font.setWeight(75)
        # self.label_24.setFont(font)
        # self.label_24.setStyleSheet("color :rgb(255, 255, 255)")
        # self.label_24.setOpenExternalLinks(True)
        # self.label_24.setObjectName("label_24")
        # self.verticalLayout_2.addWidget(self.label_24)
        # self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        # font = QtGui.QFont()
        # font.setFamily("Agency FB")
        # font.setPointSize(12)
        # font.setBold(True)
        # font.setWeight(75)
        # self.label_31.setFont(font)
        # self.label_31.setStyleSheet("color :rgb(255, 255, 255)")
        # self.label_31.setOpenExternalLinks(True)
        # self.label_31.setObjectName("label_31")
        # self.verticalLayout_2.addWidget(self.label_31)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_32.setOpenExternalLinks(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_33.setOpenExternalLinks(True)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_37.setOpenExternalLinks(True)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_2.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_38.setOpenExternalLinks(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_2.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_39.setOpenExternalLinks(True)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_2.addWidget(self.label_39)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_34.setOpenExternalLinks(True)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.label_34)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_2.addWidget(self.label_29)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_22.setOpenExternalLinks(True)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_35.setOpenExternalLinks(True)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_2.addWidget(self.label_35)

        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_20.setOpenExternalLinks(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color :rgb(255, 255, 255)")
        self.label_21.setOpenExternalLinks(True)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)

        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1722, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "题目列表"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'宋体\'; font-size:16pt;   color:#ffffff;\">第一章 信息系统和管理</span></p></body></html>"))
        # self.label_36.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><a href=\"#\"><span style=\" font-size:16pt; text-decoration: underline; color:#ffffff;\">第二章 管理信息系统概论 </span></a></p></body></html>"))
        # self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><a href=\"#\"><span style=\" font-size:16pt; text-decoration: underline; color:#ffffff;\">第三章 管理信息系统的技术基础 </span></a></p></body></html>"))
        # self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" font-size:16pt; text-decoration: underline; color:#ffffff;\">第四章 管理信息系统的战略规划和开发方法</span></a></p></body></html>"))
        # self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" font-size:16pt; text-decoration: underline; color:#ffffff;\">第五章 管理信息系统的系统分析</span></a></p></body></html>"))
        #修改，去掉超链接
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第二章 管理信息系统概论</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第三章 管理信息系统的技术基础</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第四章 管理信息系统的战略规划和开发方法</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第五章 管理信息系统的系统分析</span></p></body></html>"))


        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第六章 管理信息系统的系统设计</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><a href='6.1jiaoyan.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">6.1 校验位设计</span></a></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><a href='6.2professors.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">6.2 屏幕输入及输入校验设计</span></a></p></body></html>"))
        #self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">6.3 输入校验设计</span></a></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第七章 管理信息系统的系统实施</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第八章 面向对象的系统开发</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第九章 信息系统的开发技术</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><a href='\"#\"'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">9.1 用户端：学生选课App</span></a></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><a href='login.html'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">9.2 服务端：选课数据管理系统</span></a></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;  color:#ffffff;\">第十章 信息系统项目的管理与系统运维</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;  color:#ffffff;\">第十一章 决策支持系统 </span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><a href='11.1order-goods.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">11.1 订货处理系统</span></a></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><a href='11.2nego-sys.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">11.2 基于冲突消解的谈判支持系统</span></a></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十二章 电子商务</span></p></body></html>"))

        #修改，去掉超链接
        # self.label_17.setText(_translate("MainWindow", "<a href = \'#\'><html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十三章 电子政务</span></p></body></html></a>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十三章 电子政务</span></p></body></html>"))
        #增加，增加12.3 关键字竞价排名
        self.label_123.setText(_translate("MainWindow", "<html><head/><body><p><a href='12.3Auction.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">12.1 关键字竞价排名</span></a></p></body></html>"))

        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十四章 电子健康</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><a href='14.1doctor.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">14.1 医患交互系统——医生子系统</span></a></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><a href='14.2patient.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">14.2 医患交互系统——患者子系统</span></a></p></body></html>"))
    #    self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">14.3 日常管理演示</span></a></p></body></html>"))
    #    self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">14.4 在线药房演示</span></a></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十五章 跨组织的信息系统管理</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><a href='15.1xuanzhi.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">15.1 配送中心选址</span></a></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><a href='15.2beiyesi.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">15.2 基于朴素贝叶斯算法的银行用户信用等级分类</span></a></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十六章 数据分析</span></p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><a href='16.1douban.html'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">16.1 豆瓣电影信息爬虫的实现</span></a></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><a href='16.2K-Means.html'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">16.2 基于K-Means算法的航空公司客户价值细分的实现 </span></a></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><a href=16.3survival-regression.html><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">16.3 关于电信公司客户流失的生存回归分析</span></a></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十七章 管理系统模拟概论</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><a href='17.1ATM.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">17.1 ATM排队模拟系统</span></a></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">第十八章 数据库信息安全</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><a href='18.1SQL-input.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">18.1 企业工资系统SQL注入演示</span></a></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><a href='18.2app.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">18.2 电子病历防篡改存档演示</span></a></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><a href='18.3encrypt-algorithom.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">18.3 加密算法</span></a></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><a href='18.4access-ritht.exe'><span style=\" font-weight:400; text-decoration: underline; color:#ffffff;\">18.4 存取检验</span></a></p></body></html>"))
