# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TotalInterface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TotalInterface(object):
    def setupUi(self, TotalInterface):
        TotalInterface.setObjectName("TotalInterface")
        TotalInterface.resize(666, 421)
        self.Start = QtWidgets.QPushButton(TotalInterface)
        self.Start.setGeometry(QtCore.QRect(60, 60, 75, 25))
        self.Start.setObjectName("Start")
        self.Quit = QtWidgets.QPushButton(TotalInterface)
        self.Quit.setGeometry(QtCore.QRect(210, 60, 75, 25))
        self.Quit.setObjectName("Quit")
        self.Description = QtWidgets.QLabel(TotalInterface)
        self.Description.setGeometry(QtCore.QRect(20, 10, 625, 40))
        self.Description.setWordWrap(True)
        self.Description.setObjectName("Description")
        self.Negotiation_txt = QtWidgets.QPlainTextEdit(TotalInterface)
        self.Negotiation_txt.setGeometry(QtCore.QRect(14, 124, 311, 280))
        self.Negotiation_txt.setPlainText("")
        self.Negotiation_txt.setObjectName("Negotiation_txt")
        self.Scene = QtWidgets.QLabel(TotalInterface)
        self.Scene.setGeometry(QtCore.QRect(140, 100, 61, 16))
        self.Scene.setObjectName("Scene")
        self.Data = QtWidgets.QLabel(TotalInterface)
        self.Data.setGeometry(QtCore.QRect(500, 60, 91, 16))
        self.Data.setObjectName("Data")
        self.A = QtWidgets.QLabel(TotalInterface)
        self.A.setGeometry(QtCore.QRect(380, 100, 41, 21))
        self.A.setMinimumSize(QtCore.QSize(0, 0))
        self.A.setObjectName("A")
        self.Profit = QtWidgets.QLabel(TotalInterface)
        self.Profit.setGeometry(QtCore.QRect(380, 130, 30, 21))
        self.Profit.setMinimumSize(QtCore.QSize(0, 0))
        self.Profit.setObjectName("Profit")
        self.A_priority = QtWidgets.QLabel(TotalInterface)
        self.A_priority.setGeometry(QtCore.QRect(450, 100, 51, 21))
        self.A_priority.setMinimumSize(QtCore.QSize(0, 0))
        self.A_priority.setObjectName("A_priority")
        self.Priority_A = QtWidgets.QLineEdit(TotalInterface)
        self.Priority_A.setEnabled(True)
        self.Priority_A.setGeometry(QtCore.QRect(450, 130, 50, 20))
        self.Priority_A.setText("")
        self.Priority_A.setObjectName("Priority_A")
        self.A_expect = QtWidgets.QLabel(TotalInterface)
        self.A_expect.setGeometry(QtCore.QRect(520, 100, 51, 21))
        self.A_expect.setObjectName("A_expect")
        self.Expect_A = QtWidgets.QLineEdit(TotalInterface)
        self.Expect_A.setGeometry(QtCore.QRect(520, 130, 51, 20))
        self.Expect_A.setObjectName("Expect_A")
        self.A_relaxValue = QtWidgets.QLabel(TotalInterface)
        self.A_relaxValue.setGeometry(QtCore.QRect(600, 100, 61, 21))
        self.A_relaxValue.setObjectName("A_relaxValue")
        self.RelaxValue_A = QtWidgets.QLineEdit(TotalInterface)
        self.RelaxValue_A.setGeometry(QtCore.QRect(600, 130, 51, 20))
        self.RelaxValue_A.setObjectName("RelaxValue_A")
        self.B = QtWidgets.QLabel(TotalInterface)
        self.B.setGeometry(QtCore.QRect(380, 170, 41, 21))
        self.B.setObjectName("B")
        self.UnitPrice = QtWidgets.QLabel(TotalInterface)
        self.UnitPrice.setGeometry(QtCore.QRect(380, 200, 61, 21))
        self.UnitPrice.setObjectName("UnitPrice")
        self.B_priority = QtWidgets.QLabel(TotalInterface)
        self.B_priority.setGeometry(QtCore.QRect(450, 170, 51, 21))
        self.B_priority.setObjectName("B_priority")
        self.Priority_B = QtWidgets.QLineEdit(TotalInterface)
        self.Priority_B.setEnabled(True)
        self.Priority_B.setGeometry(QtCore.QRect(450, 200, 51, 20))
        self.Priority_B.setDragEnabled(False)
        self.Priority_B.setReadOnly(False)
        self.Priority_B.setObjectName("Priority_B")
        self.B_expect = QtWidgets.QLabel(TotalInterface)
        self.B_expect.setGeometry(QtCore.QRect(520, 170, 51, 21))
        self.B_expect.setObjectName("B_expect")
        self.Expect_B = QtWidgets.QLineEdit(TotalInterface)
        self.Expect_B.setGeometry(QtCore.QRect(520, 200, 51, 20))
        self.Expect_B.setObjectName("Expect_B")
        self.B_relaxValue = QtWidgets.QLabel(TotalInterface)
        self.B_relaxValue.setGeometry(QtCore.QRect(600, 170, 61, 21))
        self.B_relaxValue.setObjectName("B_relaxValue")
        self.RelaxValue_B = QtWidgets.QLineEdit(TotalInterface)
        self.RelaxValue_B.setGeometry(QtCore.QRect(600, 200, 51, 20))
        self.RelaxValue_B.setObjectName("RelaxValue_B")
        self.C = QtWidgets.QLabel(TotalInterface)
        self.C.setGeometry(QtCore.QRect(380, 240, 41, 21))
        self.C.setObjectName("C")
        self.TotalCost = QtWidgets.QLabel(TotalInterface)
        self.TotalCost.setGeometry(QtCore.QRect(340, 270, 111, 21))
        self.TotalCost.setObjectName("TotalCost")
        self.UnitCost = QtWidgets.QLabel(TotalInterface)
        self.UnitCost.setGeometry(QtCore.QRect(330, 300, 121, 21))
        self.UnitCost.setObjectName("UnitCost")
        self.C_priority = QtWidgets.QLabel(TotalInterface)
        self.C_priority.setGeometry(QtCore.QRect(450, 240, 51, 21))
        self.C_priority.setObjectName("C_priority")
        self.Priority_C_total = QtWidgets.QLineEdit(TotalInterface)
        self.Priority_C_total.setGeometry(QtCore.QRect(450, 270, 51, 20))
        self.Priority_C_total.setObjectName("Priority_C_total")
        self.Priority_C_unit = QtWidgets.QLineEdit(TotalInterface)
        self.Priority_C_unit.setGeometry(QtCore.QRect(450, 300, 51, 20))
        self.Priority_C_unit.setObjectName("Priority_C_unit")
        self.C_expect = QtWidgets.QLabel(TotalInterface)
        self.C_expect.setGeometry(QtCore.QRect(520, 240, 51, 21))
        self.C_expect.setObjectName("C_expect")
        self.Expect_C_total = QtWidgets.QLineEdit(TotalInterface)
        self.Expect_C_total.setGeometry(QtCore.QRect(520, 270, 51, 20))
        self.Expect_C_total.setObjectName("Expect_C_total")
        self.Expect_C_unit = QtWidgets.QLineEdit(TotalInterface)
        self.Expect_C_unit.setGeometry(QtCore.QRect(520, 300, 51, 20))
        self.Expect_C_unit.setObjectName("Expect_C_unit")
        self.C_relaxValue = QtWidgets.QLabel(TotalInterface)
        self.C_relaxValue.setGeometry(QtCore.QRect(600, 240, 61, 21))
        self.C_relaxValue.setObjectName("C_relaxValue")
        self.RelaxValue_C_total = QtWidgets.QLineEdit(TotalInterface)
        self.RelaxValue_C_total.setGeometry(QtCore.QRect(600, 270, 51, 20))
        self.RelaxValue_C_total.setObjectName("RelaxValue_C_total")
        self.RelaxValue_C_unit = QtWidgets.QLineEdit(TotalInterface)
        self.RelaxValue_C_unit.setGeometry(QtCore.QRect(600, 300, 51, 20))
        self.RelaxValue_C_unit.setObjectName("RelaxValue_C_unit")
        self.D = QtWidgets.QLabel(TotalInterface)
        self.D.setGeometry(QtCore.QRect(380, 340, 41, 21))
        self.D.setObjectName("D")
        self.ShipFee = QtWidgets.QLabel(TotalInterface)
        self.ShipFee.setGeometry(QtCore.QRect(380, 370, 51, 21))
        self.ShipFee.setObjectName("ShipFee")
        self.D_priority = QtWidgets.QLabel(TotalInterface)
        self.D_priority.setGeometry(QtCore.QRect(450, 340, 51, 21))
        self.D_priority.setObjectName("D_priority")
        self.D_expect = QtWidgets.QLabel(TotalInterface)
        self.D_expect.setGeometry(QtCore.QRect(520, 340, 51, 21))
        self.D_expect.setObjectName("D_expect")
        self.D_relaxValue = QtWidgets.QLabel(TotalInterface)
        self.D_relaxValue.setGeometry(QtCore.QRect(600, 340, 61, 21))
        self.D_relaxValue.setObjectName("D_relaxValue")
        self.Priority_D = QtWidgets.QLineEdit(TotalInterface)
        self.Priority_D.setGeometry(QtCore.QRect(450, 370, 51, 20))
        self.Priority_D.setBaseSize(QtCore.QSize(0, 0))
        self.Priority_D.setObjectName("Priority_D")
        self.Expect_D = QtWidgets.QLineEdit(TotalInterface)
        self.Expect_D.setGeometry(QtCore.QRect(520, 370, 51, 20))
        self.Expect_D.setObjectName("Expect_D")
        self.RelaxValue_D = QtWidgets.QLineEdit(TotalInterface)
        self.RelaxValue_D.setGeometry(QtCore.QRect(600, 370, 51, 20))
        self.RelaxValue_D.setObjectName("RelaxValue_D")
        self.Start.raise_()
        self.Quit.raise_()
        self.Description.raise_()
        self.Negotiation_txt.raise_()
        self.Scene.raise_()
        self.Data.raise_()
        self.A_relaxValue.raise_()
        self.A.raise_()
        self.Profit.raise_()
        self.A_priority.raise_()
        self.Priority_A.raise_()
        self.A_expect.raise_()
        self.Expect_A.raise_()
        self.RelaxValue_A.raise_()
        self.B.raise_()
        self.UnitPrice.raise_()
        self.B_priority.raise_()
        self.Priority_B.raise_()
        self.B_expect.raise_()
        self.Expect_B.raise_()
        self.B_relaxValue.raise_()
        self.RelaxValue_B.raise_()
        self.C.raise_()
        self.TotalCost.raise_()
        self.UnitCost.raise_()
        self.C_priority.raise_()
        self.Priority_C_total.raise_()
        self.Priority_C_unit.raise_()
        self.C_expect.raise_()
        self.Expect_C_total.raise_()
        self.Expect_C_unit.raise_()
        self.C_relaxValue.raise_()
        self.RelaxValue_C_total.raise_()
        self.RelaxValue_C_unit.raise_()
        self.D.raise_()
        self.ShipFee.raise_()
        self.D_priority.raise_()
        self.D_expect.raise_()
        self.D_relaxValue.raise_()
        self.Priority_D.raise_()
        self.Expect_D.raise_()
        self.RelaxValue_D.raise_()

        self.retranslateUi(TotalInterface)
        QtCore.QMetaObject.connectSlotsByName(TotalInterface)

    def retranslateUi(self, TotalInterface):
        _translate = QtCore.QCoreApplication.translate
        TotalInterface.setWindowTitle(_translate("TotalInterface", "Form"))
        self.Start.setText(_translate("TotalInterface", "开始谈判"))
        self.Quit.setText(_translate("TotalInterface", "退出系统"))
        self.Description.setText(_translate("TotalInterface", "说明：用户直接点击“开始谈判”按钮后显示谈判过程和谈判结果，企业的期望值和可放松值可在右下侧进行自主输入修改，之后点击“开始谈判”按钮即可进行新的谈判。"))
        self.Scene.setText(_translate("TotalInterface", "谈判情景"))
        self.Data.setText(_translate("TotalInterface", "谈判数据录入"))
        self.A.setText(_translate("TotalInterface", "企业A"))
        self.Profit.setText(_translate("TotalInterface", "利润"))
        self.A_priority.setText(_translate("TotalInterface", "优先级"))
        self.A_expect.setText(_translate("TotalInterface", "期望值"))
        self.A_relaxValue.setText(_translate("TotalInterface", "可放松值"))
        self.B.setText(_translate("TotalInterface", "企业B"))
        self.UnitPrice.setText(_translate("TotalInterface", "购买单价"))
        self.B_priority.setText(_translate("TotalInterface", "优先级"))
        self.B_expect.setText(_translate("TotalInterface", "期望值"))
        self.B_relaxValue.setText(_translate("TotalInterface", "可放松值"))
        self.C.setText(_translate("TotalInterface", "企业C"))
        self.TotalCost.setText(_translate("TotalInterface", "原料固定总费用"))
        self.UnitCost.setText(_translate("TotalInterface", "原料变动单位费用"))
        self.C_priority.setText(_translate("TotalInterface", "优先级"))
        self.C_expect.setText(_translate("TotalInterface", "期望值"))
        self.C_relaxValue.setText(_translate("TotalInterface", "可放松值"))
        self.D.setText(_translate("TotalInterface", "企业D"))
        self.ShipFee.setText(_translate("TotalInterface", "运输费"))
        self.D_priority.setText(_translate("TotalInterface", "优先级"))
        self.D_expect.setText(_translate("TotalInterface", "期望值"))
        self.D_relaxValue.setText(_translate("TotalInterface", "可放松值"))

if __name__=="__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TotalInterface()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())